# Site settings
title: "Brian Bunke"
email: me@brianbunke.com
description: "...And You Will Know Me by the Trail of Documentation"
baseurl: ""
url: "https://brianbunke.github.io"
title_description: "IT Lead in the Seattle area. I often write about PowerShell and VMware. My sons think I'm funny sometimes.
<br><br>
<a href=\"https://vexpert.vmware.com/directory/1581\"><img src=\"/images/vExpert.png\"></a> 
<a href=\"https://www.certmetrics.com/vmware/public/transcript.aspx?transcript=475K7SWC2N41QLWF\"><img src=\"/images/vcert.png\"></a>"
title_image: "/images/brian.jpg"
google_analytics: "UA-59218526-2"
github_repository: https://github.com/brianbunke/brianbunke.github.io
post_limit: 5
# disqus_account: insert-here
# addthis_id: insert-here

# Social usernames/URLs
twitter_username: brianbunke
github_username:  brianbunke
reddit_username:  brianbunke
linkedin_link:    brianbunke
instagram_username: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "<a href=\"https://jekyllrb.com\">Jekyll</a> | <a href=\"https://pages.github.com\">GitHub Pages</a> | <a href=\"https://github.com/jacobtomlinson/carte-noire\">Carte Noire</a>"
footer_right: "<a href=\"https://github.com/brianbunke/brianbunke.github.io\"><i class=\"fa fa-code\"></i><i class=\"fab fa-github\"></i></a>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM

permalink: pretty
exclude: [vendor]
future: false
